package co.edu.uniquindio.empresa;

public enum Marca {

	ACURA, ALFA_ROMEO, APTERA, ASTON_MARTIN, AUDI, AUSTIN, BENTLEY, BMW, BUGATTI, BUICK, CADILLAC, CHEVROLET, CHRYSLER,
	CITROËN, CORBIN, DAEWOO, DAIHATSU, DODGE, EAGLE, FAIRTHORPE, FERRARI, FIAT, FILLMORE, FOOSE, FORD, GEO, GMC,
	HILLMAN, HOLDEN, HONDA, HUMMER, HYUNDAI, INFINITI, ISUZU, JAGUAR, JEEP, JENSEN, KIA, LAMBORGHINI, LAND_ROVER, LEXUS,
	LINCOLN, LOTUS, MASERATI, MAYBACH, MAZDA, MCLAREN, MERCEDES_BENZ, MERCURY, MERKUR, MG, MINI, MITSUBISHI, MORGAN,
	NISSAN, OLDSMOBILE, PANOZ, PEUGEOT, PLYMOUTH, PONTIAC, PORSCHE, RAM, RAMBLER, RENAULT, ROLLS_ROYCE, SAAB, SATURN,
	SCION, SHELBY, SMART, SPYKER, SPYKER_CARS, STUDEBAKER, SUBARU, SUZUKI, TESLA, TOYOTA, VOLKSWAGEN, VOLVO
}
